//-----------------------------------------------------------------------
// <copyright file="AutoGeneratedQTests.cs" company="Microsoft">
//     Copyright (c) Microsoft Corporation.  All rights reserved.
//    
//    The use and distribution terms for this software are covered by the
//    Common Public License 1.0 (http://opensource.org/licenses/cpl.php)
//    which can be found in the file CPL.TXT at the root of this distribution.
//    By using this software in any fashion, you are agreeing to be bound by
//    the terms of this license.
//    
//    You must not remove this notice, or any other, from this software.
// </copyright>
// <summary>
//     Contains test methods for the QTests
// </summary>
//-----------------------------------------------------------------------

namespace Microsoft.Tools.WindowsInstallerXml.Test.Tests
{
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Microsoft.Tools.WindowsInstallerXml.Test;

    /// <summary>
    /// Contains test methods for the QTests
    /// </summary>
    public partial class QTests : WixTests
    {
        //[TestMethod]
        //[Description("Example QTest")]
        //[Priority(2)]
        //public void ExampleQTest()
        //{
        //    wixUnit.RunTest("ExampleQTest");
        //}
   }
}
