/* **************************************************************************
 * C:\delivery\Dev\wix36_public\inc\wixver.h - version information for project
 *
 * 2011.3.18 - generated by build system.
 * **************************************************************************/

#ifndef _VERSION_FILE_H_
#define _VERSION_FILE_H_

#define szVerMajorMinor "3.6"
#define szVerMajorMinorBuild "3.6.1518.0"
#define rmj	3
#define rmm	6
#define rup	1518
#define szVerName	"Official Release"

#endif // _VERSION_FILE_H_
