//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Tools.WindowsInstallerXml.Bootstrapper {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserInterfaceResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserInterfaceResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Tools.WindowsInstallerXml.Bootstrapper.UserInterfaceResources", typeof(UserInterfaceResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string ChangeHeading {
            get {
                return ResourceManager.GetString("ChangeHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifying.
        /// </summary>
        internal static string ChangeProgress {
            get {
                return ResourceManager.GetString("ChangeProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to changing.
        /// </summary>
        internal static string ChangingFeature {
            get {
                return ResourceManager.GetString("ChangingFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to downloading.
        /// </summary>
        internal static string DownloadingFeature {
            get {
                return ResourceManager.GetString("DownloadingFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} failed.
        /// </summary>
        internal static string ExecutionFailure {
            get {
                return ResourceManager.GetString("ExecutionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was successful.
        /// </summary>
        internal static string ExecutionSuccess {
            get {
                return ResourceManager.GetString("ExecutionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup is {0} the following feature:.
        /// </summary>
        internal static string FeatureProgress {
            get {
                return ResourceManager.GetString("FeatureProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation.
        /// </summary>
        internal static string InstallationHeading {
            get {
                return ResourceManager.GetString("InstallationHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading and installing.
        /// </summary>
        internal static string InstallationProgress {
            get {
                return ResourceManager.GetString("InstallationProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to installing.
        /// </summary>
        internal static string InstallingFeature {
            get {
                return ResourceManager.GetString("InstallingFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select additional programs you want to install and unselect the ones you want to uninstall:.
        /// </summary>
        internal static string ProgramsToChange {
            get {
                return ResourceManager.GetString("ProgramsToChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the programs you want to install:.
        /// </summary>
        internal static string ProgramsToInstall {
            get {
                return ResourceManager.GetString("ProgramsToInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the programs you want to repair:.
        /// </summary>
        internal static string ProgramsToRepair {
            get {
                return ResourceManager.GetString("ProgramsToRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the programs you want to uninstall:.
        /// </summary>
        internal static string ProgramsToUninstall {
            get {
                return ResourceManager.GetString("ProgramsToUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair.
        /// </summary>
        internal static string RepairHeading {
            get {
                return ResourceManager.GetString("RepairHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to repairing.
        /// </summary>
        internal static string RepairingFeature {
            get {
                return ResourceManager.GetString("RepairingFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repairing.
        /// </summary>
        internal static string RepairProgress {
            get {
                return ResourceManager.GetString("RepairProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstallation.
        /// </summary>
        internal static string UninstallationHeading {
            get {
                return ResourceManager.GetString("UninstallationHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling.
        /// </summary>
        internal static string UninstallationProgress {
            get {
                return ResourceManager.GetString("UninstallationProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uninstalling.
        /// </summary>
        internal static string UninstallingFeature {
            get {
                return ResourceManager.GetString("UninstallingFeature", resourceCulture);
            }
        }
    }
}
